# Generated by Django 6.0.2 on 2026-02-21 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Hard', 'Hard')], max_length=10)),
                ('duration_minutes', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('buggy_code_c', models.TextField(blank=True, null=True)),
                ('buggy_code_python', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField(blank=True, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='events.round')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('member1_name', models.CharField(max_length=100)),
                ('member1_email', models.EmailField(max_length=254)),
                ('member1_roll', models.CharField(max_length=50)),
                ('member2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('member2_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('member2_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('tab_switches', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='events.problem')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='events.team')),
            ],
            options={
                'unique_together': {('team', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='RoundParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('C', 'C'), ('Python', 'Python')], max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_malpractice', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.team')),
            ],
            options={
                'unique_together': {('team', 'round')},
            },
        ),
    ]
