# Generated by Django 6.0.2 on 2026-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundparticipation',
            name='assigned_problems',
            field=models.ManyToManyField(blank=True, to='events.problem'),
        ),
    ]
