# Generated by Django 6.0.2 on 2026-02-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_roundparticipation_assigned_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score_errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_logic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_structure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_tabs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_time',
            field=models.IntegerField(default=0),
        ),
    ]
